# DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/microleaf
spring.datasource.username=postgres
spring.datasource.password=MahatoPG26
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Service Registry URL
eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka
